spring.profiles.include: devdb

server.port: 7001
server.error.include-message: always

logging:
  level:
    root: INFO
    org.caltech.miniswing: DEBUG
    com:
      querydsl:
        sql: DEBUG
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

---
spring.profiles: docker

server.port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysql-customer/customer