server.port: 7004
server.error.include-message: always

logging:
  level:
    root: INFO
    org.caltech.miniswing: INFO
    com:
      querydsl:
        sql: INFO
    org:
      hibernate:
        type:
          descriptor:
            sql: INFO

spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings:
    serviceOutput:
      destination: service
      producer:
        required-groups: auditGroup

    productInput:
      destination: product
      group: productSubGroup
      consumer:
        maxAttempts: 3
        backOffInitialInterval: 500
        backOffMaxInterval: 1000
        backOffMultiplier: 2.0

    billingInput:
      destination: billing
      group: billingSubGroup
      consumer:
        maxAttempts: 3
        backOffInitialInterval: 500
        backOffMaxInterval: 1000
        backOffMultiplier: 2.0

spring.cloud.stream.rabbit.bindings.input-product.consumer:
  autoBindDlq: true
  republishToDlq: true

spring.cloud.stream.rabbit.bindings.input-billing.consumer:
  autoBindDlq: true
  republishToDlq: true

spring:
  jpa:
    show_sql: true
    format_sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect

  datasource:
    initialization-mode: always
    url: jdbc:mysql://localhost:13309/service
    username: user
    password: pwd
    driver-class-name: com.mysql.cj.jdbc.Driver
    #schema: classpath*:db/mysql/schema.sql

---
spring.profiles: docker

server.port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysql-service/service
