version: '3'

services:
  mysql-plm:
    image: mysql:5.7
    mem_limit: 350m
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=plm
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    healthcheck:
      test: "/usr/bin/mysql --user=user --password=pwd --execute \"SHOW DATABASES;\""
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - ./mysql-custom.cnf:/etc/mysql/conf.d/custom.cnf
      - /Users/realimpact/Documents/swingdb/plm:/var/lib/mysql

  mysql-product:
    image: mysql:5.7
    mem_limit: 350m
    ports:
      - "13307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=product
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    healthcheck:
      test: "/usr/bin/mysql --user=user --password=pwd --execute \"SHOW DATABASES;\""
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - ./mysql-custom.cnf:/etc/mysql/conf.d/custom.cnf
      - /Users/realimpact/Documents/swingdb/product:/var/lib/mysql

  mysql-customer:
    image: mysql:5.7
    mem_limit: 350m
    ports:
      - "13308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=customer
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    healthcheck:
      test: "/usr/bin/mysql --user=user --password=pwd --execute \"SHOW DATABASES;\""
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - ./mysql-custom.cnf:/etc/mysql/conf.d/custom.cnf
      - /Users/realimpact/Documents/swingdb/customer:/var/lib/mysql

  mysql-service:
    image: mysql:5.7
    mem_limit: 350m
    ports:
      - "13309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=service
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    healthcheck:
      test: "/usr/bin/mysql --user=user --password=pwd --execute \"SHOW DATABASES;\""
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - ./mysql-custom.cnf:/etc/mysql/conf.d/custom.cnf
      - /Users/realimpact/Documents/swingdb/service:/var/lib/mysql

  prod:
    build: microservices/product-service/product-server
    mem_limit: 350m
    ports:
      - "7003:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - TZ=Asia/Seoul
      - SPRING_CLOUD_STREAM_DEFAULTBINDER=kafka
      - SPRING_CLOUD_STREAM_BINDINGS_INPUT_CONSUMER_PARTITIONED=false
    depends_on:
      mysql-product:
        condition: service_healthy
      kafka:
        condition: service_started

  plm:
    build: microservices/plm-service/plm-server
    mem_limit: 350m
    ports:
      - "7002:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - TZ=Asia/Seoul
      - SPRING_CLOUD_STREAM_DEFAULTBINDER=kafka
      - SPRING_CLOUD_STREAM_BINDINGS_INPUT_CONSUMER_PARTITIONED=false
    depends_on:
      mysql-plm:
        condition: service_healthy
      kafka:
        condition: service_started

  customer:
    build: microservices/customer-service/customer-server
    mem_limit: 350m
    ports:
      - "7001:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - TZ=Asia/Seoul
      - SPRING_CLOUD_STREAM_DEFAULTBINDER=kafka
      - SPRING_CLOUD_STREAM_BINDINGS_INPUT_CONSUMER_PARTITIONED=false
    depends_on:
      mysql-customer:
        condition: service_healthy
      kafka:
        condition: service_started

  service:
    build: microservices/service-service/service-server
    mem_limit: 350m
    ports:
      - "7004:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - TZ=Asia/Seoul
      - SPRING_CLOUD_STREAM_DEFAULTBINDER=kafka
      - SPRING_CLOUD_STREAM_BINDINGS_INPUT_CONSUMER_PARTITIONED=false
    depends_on:
      mysql-service:
        condition: service_healthy
      kafka:
        condition: service_started

  kafka:
    image: wurstmeister/kafka:2.12-2.1.0
    mem_limit: 350m
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper


  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    mem_limit: 350m
    ports:
      - "2181:2181"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper
