server.port: 7003
server.error.include-message: always

spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        # Strongly recommend to set this property to "none" in a production environment!
        ddl-auto: update

logging:
  level:
    root: INFO
    org.caltech.miniswingpilot.domain: DEBUG
    com:
      querydsl:
        sql: DEBUG
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

app:
  plm-service:
    host: localhost
    port: 7002
  svc-service:
    host: localhost
    port: 7004

---
spring.profiles: docker

server.port: 8080

spring.datasource.url: jdbc:mysql://mysql_product/msa

app:
  plm-service:
    host: plm
    port: 8080
  svc-service:
    host: svc
    port: 8080