spring.profiles.include: devdb

server.port: 7003
server.error.include-message: always

logging:
  level:
    root: INFO
    org.caltech.miniswing: DEBUG
    com:
      querydsl:
        sql: DEBUG
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

app:
  plm-service:
    host: localhost
    port: 7002
  svc-service:
    host: localhost
    port: 7004

---
spring.profiles: docker

server.port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysql-product/product

app:
  plm-service:
    host: plm
    port: 8080
  svc-service:
    host: svc
    port: 8080