spring.profiles.include: devdb

server.port: 7003
server.error.include-message: always

spring.application.name: product

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

ribbon.ServerListRefreshInterval: 5000
ribbon.NFLoadBalancerPingInterval: 5

logging:
  level:
    root: INFO
    org.caltech.miniswing: DEBUG
    com:
      querydsl:
        sql: DEBUG
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings:
    productOutput:
      destination: product
      producer:
        required-groups: auditGroup
    serviceInput:
      destination: service
      group: serviceSubGroup
      consumer:
        maxAttempts: 3
        backOffInitialInterval: 500
        backOffMaxInterval: 1000
        backOffMultiplier: 2.0

spring.cloud.stream.rabbit.bindings.input-service.consumer:
  autoBindDlq: true
  republishToDlq: true

spring.rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest

---
spring.profiles: docker

server.port: 8080

eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/

spring:
  datasource:
    url: jdbc:mysql://mysql-product/product

spring.rabbitmq.host: rabbitmq