server.port: 7004
server.error.include-message: always


spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        # Strongly recommend to set this property to "none" in a production environment!
        ddl-auto: update

logging:
  level:
    root: INFO
    org.caltech.miniswingpilot.domain: DEBUG
    com:
      querydsl:
        sql: DEBUG
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

app:
  prod-service:
    host: localhost
    port: 7003

  plm-service:
    host: localhost
    port: 7002

---
spring.profiles: docker

server.port: 8080

spring.datasource.url: jdbc:mysql://mysql_service/msa

app:
  prod-service:
    host: prod
    port: 8080

  plm-service:
    host: plm
    port: 8080