spring.profiles.include: devdb

server.port: 7004
server.error.include-message: always

logging:
  level:
    root: INFO
    org.caltech.miniswing: DEBUG
    com:
      querydsl:
        sql: DEBUG
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

app:
  prod-service:
    host: localhost
    port: 7003

  plm-service:
    host: localhost
    port: 7002

---
spring.profiles: docker

server.port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysql-service/service

app:
  prod-service:
    host: prod
    port: 8080

  plm-service:
    host: plm
    port: 8080