app:
  customer-service:
    host: localhost
    port: 7001
  plm-service:
    host: localhost
    port: 7002
  prod-service:
    host: localhost
    port: 7003
  svc-service:
    host: localhost
    port: 7004


---
spring.profiles: docker

app:
  customer-service:
    host: customer
    port: 8080
  plm-service:
    host: plm
    port: 8080
  prod-service:
    host: prod
    port: 8080
  svc-service:
    host: svc
    port: 8080